name: Release
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 7

      - name: Install dependencies
        run: pnpm install

      - name: Local ENV files
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
        run: |
          echo $ENV_FILE | base64 --decode > .env

      - name: Git User
        run: |
          git config user.name "${GITHUB_USERNAME}"
          git config user.email "${GITHUB_MAIL_USERNAME_ID}@users.noreply.github.com"

      - name: Set NPM TOKEN
        run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Release & Publish
        run: pnpm release --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: End
        run: echo "Done!"
